# Generated by Django 4.1.2 on 2023-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=4)),
                ('ctitle', models.CharField(max_length=4)),
                ('cname', models.CharField(max_length=255)),
                ('cclub', models.CharField(max_length=255)),
            ],
        ),
    ]
