# Generated by Django 4.1.2 on 2023-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cdiscount',
            field=models.BooleanField(default=False),
        ),
    ]
