# Generated by Django 4.1.7 on 2023-03-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_customer_cc_exp_alter_customer_cc_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age_rating', models.CharField(max_length=3)),
                ('duration', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('filmimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FilmShowings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_date', models.DateField()),
                ('ticket_quantity', models.IntegerField(default=150)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.film')),
                ('screen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.screen')),
            ],
        ),
    ]
