# Generated by Django 4.1.7 on 2023-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_film_screen_filmshowings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='age_rating',
        ),
        migrations.RemoveField(
            model_name='film',
            name='filmimage',
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='uploads/films/no-img.jpg', upload_to='uploads/films'),
        ),
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
