# Generated by Django 4.1.7 on 2023-03-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_film_age_rating_remove_film_filmimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12A', '12A'), ('12', '12'), ('15', '15'), ('18', '18')], default='U', max_length=3),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(default='No description available', max_length=500),
        ),
    ]
